language: python
python:
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
- pip install -r requirements.txt
- pip install .

script:
- export PYTHONPATH=$TRAVIS_BUILD_DIR
- python tests/test.py

script: pytest

deploy:
  provider: s3
  access_key_id: AKIAIH6I45BAJIHWYAAQ
  secret_access_key: $AWS_SECRET_KEY
  bucket: "traviscibucket"
  upload_dir: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER.$TRAVIS_COMMIT/$TRAVIS_JOB_NAME
  local_dir: $TRAVIS_BUILD_DIR/dist
  skip_cleanup: true
  on:
    all_branches: true

notifications:
  email:
    recipients:
    - carlk@msn.com
    on_success: always
    on_failure: always
