name: CI
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2022, macos-13, macos-14]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v3
    - name: Install Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}


    - name: Pinned Ruff
      run:  uvx ruff@0.7.1 check
    - name: Lastest Ruff (just to check for warnings)
      run: uvx ruff@latest check || echo "Ignoring warnings from the latest version of ruff"
    - name: Install minimal dependencies
      run: uv sync --extra dev
    - name: Run min test
      shell: bash
      run: |
        if [[ "$RUNNER_OS" != "Windows" ]]; then
          source .venv/bin/activate
        else
          source .venv/Scripts/activate
        fi
        python tests/test.py
    - name: Install all dependencies
      run: uv sync --all-extras
    - name: Run all tests
      shell: bash
      run: |
        if [[ "$RUNNER_OS" != "Windows" ]]; then
          source .venv/bin/activate
        else
          source .venv/Scripts/activate
        fi
        pytest pysnptools/distreader/test_bgen2.py

    - name: Build
      run: uv build        
    - name: Save SDist
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: dist/*.tar.gz
