name: CI
on: push
    
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, windows-latest, macOS-latest]
        python-version: [3.7] #, 3.8 ,3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Miniconda ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Conda list
      shell: pwsh
      run: conda list

    - name: Install Prerequisites
      shell: bash
      run: |
        pip install -U pip --user
        pip install -U pytest --user
        # cmk pip install -r requirements.txt --user
        pip install scipy>=1.1.0 --user
        pip install numpy>=1.11.3 --user
        pip install psutil>=5.6.7 --user
        pip install pandas>=1.1.1 --user
        pip install h5py>=2.10.0 --user
        pip install dill>=0.2.9 --user
        pip install bgen-reader==4.0.6 --user
        pip install wheel>=0.34.2 --user
        pip install --index-url https://test.pypi.org/simple/ bed-reader --user

    - name: Install Project
      shell: bash
      run: |
        python --version
        pip install .
        python setup.py sdist

    - name: Test
      shell: bash
      run: |
        pip uninstall pysnptools --yes
        export PYTHONPATH=${GITHUB_WORKSPACE}
        echo ${PYTHONPATH}
        python tests/test.py

    - name: Save SDist
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist/*.tar.gz
